files:
  - source: /test.strings
    translation: /translations/%two_letters_code%/%original_file_name%
  - source: /webwallet/newStrings.js
    translation: /translations/%two_letters_code%/%original_file_name%
  - source: /server/
    translation: /server/%two_letters_code%/%original_file_name%
